server:
  port: 7002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

logging:
  level:
    root: INFO
    microservices: DEBUG
    org.springframework.data.mongodb.core.MogoTemplate: DEBUG