server:
  port: 7002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
  cloud:
    stream:
      default-binder: kafka
      default.contentType: application/json
      bindings:
        input:
          destination: recommendations
          group: recommendationGroup
          consumer:
            maxAttemps: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrockerPort: 9092

logging:
  level:
    root: INFO
    microservices: DEBUG
    org.springframework.data.mongodb.core.MogoTemplate: DEBUG