server:
  port: 7001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
  cloud:
    stream:
      default-binder: kafka
      default.contentType: application/json
      bindings:
        input:
          destination: products # 토픽
          group: productGroup # 컨슈머 그룹
          consumer:
            # Dead Letter 처리를 위한 설정
            maxAttemps: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    root: INFO
    microservices: DEBUG
    org.springframework.data.mongodb.core.MogoTemplate: DEBUG