server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongodb
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka

eureka:
  client:
    service-url: http://eureka:8761/eureka