server:
  port: 7003

spring:
  application:
    name: review
  datasource:
    url: jdbc:mysql://localhost:3306/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      default-binder: kafka
      default.contentType: application/json
      bindings:
        input:
          destination: reviews
          group: reviewGroup
          comsumer:
            maxAttemps: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrockerPort: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5

logging:
  lovel:
    root: INFO
    microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE