server:
  port: 7003


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
    maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      default-binder: kafka
      default:
        contentType: application/json
      bindings:
        input:  # input channel
          destination: reviews  # topic
          group: reviesGroup
          consumer:
            maxAttemps: 3
            backOffInitnialInterval: 500
            backOffMaxInter val: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
        bindings:
          input:
            consumer:
              enableDlq: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  lovel:
    root: INFO
    microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE