server:
  port: 7003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      default-binder: kafka
      default.contentType: application/json
      bindings:
        input:
          destination: reviews
          group: reviewGroup
          comsumer:
            maxAttemps: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrockerPort: 9092

logging:
  lovel:
    root: INFO
    microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE