server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/review-db
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka

eureka:
  client:
    service-url: http://eureka:8761/eureka