### Create Product
POST http://localhost:8080/product-composite
Content-Type: application/json

{
  "productId": 7,
  "name": "test product",
  "weight": 100,
  "recommendations": [
    {
      "recommendationId": 14,
      "author": "test author",
      "rate": 10,
      "content": "very good"
    },
    {
      "recommendationId": 15,
      "author": "test author2",
      "rate": 8,
      "content": "very good2"
    }
  ],
  "reviews": [
  {
    "reviewId": 16,
    "author": "review author",
    "subject": "review subject",
    "content": "good review"
  },
  {
    "reviewId": 17,
    "author": "review author2",
    "subject": "review subject2",
    "content": "good review2"
  }]
}

### Get Product
GET http://localhost:8080/product-composite/7
Content-Type: application/json

### Delete Product
DELETE http://localhost:7000/product-composite/{{productId}}
Content-Type: application/json